### ISSUE TITLE
vscode: GAMS executable not found! 

### ISSUE THREAD

**Issue by ds2010** [GAMS-dev/gams.jl#7] opened 2021-02-10 19:58 UTC
Hi all, 

I am now running the example model using JuMP and GAMS.jl. When using the Julia REPL on vscode, there is an error `GAMS executable not found! `. So, then I try to set the absolute PATH for GAMS.jl like `set_optimizer_attribute(model, "SysDir",` `/home/dais2/GAMS/gams34.2_linux_x64_64_sfx")`. But it still does not work.  Please find the error in the attached screenshot.

![Screenshot from 2021-02-10 21-23-07](https://user-images.githubusercontent.com/57257137/107563168-66bac400-6be9-11eb-9023-7a6bccd38e43.png)

Interestingly, when running the same model through the terminal using `julia test_gms.jl`, I obtain the final estimation results. 
Even when I run the code through the julia command terminal one-by-one, I can also get the results. Please note that I have defined GAMS PATH in the file `.bashrc`. 

I would like to use the GAMS.jl in the vscode, so could you please give me some suggestions to fix this issue? Many thanks in advance!

**Comment by renkekuhlmann** [comment] 2021-02-10 21:31
Thanks for the request, but unfortunately, I cannot reproduce the issue at the moment. In my VS Code Julia REPL, GAMS is found from the PATH, but I can also set the sysdir option to another directory. For the former, gams.jl basically uses `Sys.which("gams")`. So, I assume that this command doesn't find GAMS in your case?

I understand that the second option doesn't work in your case though. At the moment, GAMS is initiated trying to find GAMS from PATH and offers the option to change the sysdir later. But if the former fails, it fails. This isn't intended behaviour and will be fixed. Thanks for pointing us to this issue.

**Comment by ds2010** [comment] 2021-02-11 07:01
Thanks for your prompt reply and explanations. Indeed, the VS Code Julia REPL cannot find the GAMS PATH on my pc. But the Julia terminal can do that. Please see the following screenshot. 

![Screenshot from 2021-02-11 08-57-55](https://user-images.githubusercontent.com/57257137/107609321-44f02a00-6c47-11eb-9e77-db25dab74a45.png)
![Screenshot from 2021-02-11 08-57-37](https://user-images.githubusercontent.com/57257137/107609328-47528400-6c47-11eb-9f57-44d6fc8e29f7.png)

**Comment by renkekuhlmann** [comment] 2021-02-11 09:54
The new GAMS.jl version 0.2.1 (available in package manager soon) initializes the GAMSWorkspace within the first `JuMP.optimize!(model)` call. This way you can now set the system directory using `set_optimizer_attribute(m, GAMS.SysDir(), "<system_dir>")` before the optimization - as you do in your example above. 

Unfortunately, I don't know the reason why your VS Code Julia REPL doesn't have your correct PATH variable.

**Closed by renkekuhlmann** 2021-02-11 09:54 UTC
Labels: bug
